name: LDoc Documentation
on:
  workflow_call:
jobs:
  ldoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docs with LDoc
        uses: lunarmodules/ldoc@v1
      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/release' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs