name: Check integrity
on:
  workflow_call:
jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check icon integrity
        run: |
          python3 .github/scripts/integrity.py