name: Build
run-name: build

on: 
  push:
    branches:
      - main
      - master
    tags:
      - "*"
  

jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #    - name: Luacheck linter
  #      uses: lunarmodules/luacheck@v1
  build:
    runs-on: ubuntu-latest
    needs: ["lint"]
    steps:
      - name: set BUILD_DATE
        run: |
          echo "BUILD_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create ZIP File
        run: zip -r9 HodorReflexes-$BUILD_DATE.zip . -x *.git* *.github*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HodorReflexesZipFile
          path: HodorReflexes-$BUILD_DATE.zip
          retention-days: 1
          overwrite: true
  release-nightly:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: set BUILD_DATE
        run: |
          echo "BUILD_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: HodorReflexesZipFile
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: $BUILD_DATE
          prerelease: true
          artifacts: "HodorReflexes*.zip"
          bodyFile: "CHANGELOG.md"
  release:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: set BUILD_DATE
        run: |
          echo "BUILD_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: HodorReflexesZipFile
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: $BUILD_DATE
          artifacts: "HodorReflexes*.zip"
          bodyFile: "CHANGELOG.md"